title: Simple 
logo: 
description: A modified Minimal theme for artists
google_analytics: 
theme: jekyll-theme-minimal
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/page:num/"
plugins: 
  - jekyll-paginate
  - jekyll-feed
  
# style
body_font: Chivo Mono #font used for body text
header_font: Silkscreen #font used for title and header
background_color: "#d4cacd"
font_color: "#000"
color1: "#BB2649" #color of links and headers
color2: "#FFF" #color of links on hover
layout: #"single_column" option

# social media (full urls)
instagram: http://www.instagram.com/danaamundsen
facebook: http://www.instagram.com/danaamundsen
tumblr: http://www.instagram.com/danaamundsen
youtube: http://www.instagram.com/danaamundsen
mastodon: http://www.instagram.com/danaamundsen
kofi: http://www.instagram.com/danaamundsen
patreon: http://www.instagram.com/danaamundsen
twitch: http://www.instagram.com/danaamundsen
