title: Simple
logo: 
description: A modified Minimal theme for artists
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
excerpt_separator: <!--more-->
plugins: 
  - jekyll-paginate
  - jekyll-feed
body_font: Chivo Mono
header_font: Itim
