title: Lydia Voss
logo: /assets/img/logo.png
favicon: #eg. /assets/img/favicon.png
description: Fine art and flowers by Lydia Voss
google_analytics: 
theme: jekyll-theme-minimal
excerpt_separator: <!--more-->
paginate: 5 #Posts per page
paginate_path: "/page:num/"
plugins: 
  - jekyll-paginate
  - jekyll-feed
  
# style
google_fonts: Yes #yes or no
body_font: Lora #font used for body text
header_font: Dawning of a New Day #font used for title and header
background_color: "#82b488"
font_color: "#323d2f"
color1: "#92483c" #color of links and headers
color2: "#c5b1cf" #color of links on hover
layout: #single_column option

# social media (full urls)
instagram: 
facebook: 
tumblr: 
youtube: 
mastodon: http://socel.net/@danaamundsen
kofi: http://www.ko-fi.com/danaamundsen
patreon: 
twitch: 
