title: Simple
logo: 
description: A modified Minimal theme for artists
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
excerpt_separator: <!--more-->
plugins: 
  - jekyll-paginate
  - jekyll-feed
# style
body_font: Chivo Mono #font used for body text
header_font: Silkscreen #font used for title and header
primary_color: 
secondary_color:
highlight_color:
